### ISSUE TITLE
Feature Request: Snow forecast. 

### ISSUE THREAD

**Issue by aonghena** [WesR/RainSnek#2]
[Feature request]
If possible allow the user to ask for the snow forecast.

Thanks

**Comment by WesR** [comment]
Sounds like a good idea. I'll give it a look over tonight

**Comment by WesR** [comment]
Sorry for the delay,
Due to the depreciation of weather underground's API, the bot will need a major overhaul to another data source. Once that happens, I will include this feature. In the mean time I will mark this as closed.
